class AddStuffToRolls < ActiveRecord::Migration
  def change
    add_column :rolls, :rent_due_1814_3, :float
    add_column :rolls, :rent_paid_1814_3, :float
    add_column :rolls, :rent_owed_1814_3, :float
    add_column :rolls, :rent_ontime_1814_3, :boolean
    add_column :rolls, :rent_payment_method_1814_3, :string
    add_column :rolls, :rent_due_1814_2, :float
    add_column :rolls, :rent_paid_1814_2, :float
    add_column :rolls, :rent_owed_1814_2, :float
    add_column :rolls, :rent_ontime_1814_2, :boolean
    add_column :rolls, :rent_payment_method_1814_2, :string
    add_column :rolls, :rent_due_1814_4, :float
    add_column :rolls, :rent_paid_1814_4, :float
    add_column :rolls, :rent_owed_1814_4, :float
    add_column :rolls, :rent_ontime_1814_4, :boolean
    add_column :rolls, :rent_payment_method_1814_4, :string
    add_column :rolls, :rent_due_1814_5, :float
    add_column :rolls, :rent_paid_1814_5, :float
    add_column :rolls, :rent_owed_1814_5, :float
    add_column :rolls, :rent_ontime_1814_5, :boolean
    add_column :rolls, :rent_due_1818_1, :float
    add_column :rolls, :rent_paid_1818_1, :float
    add_column :rolls, :rent_owed_1818_1, :float
    add_column :rolls, :rent_ontime_1818_1, :boolean
    add_column :rolls, :rent_payment_method_1818_1, :string
    add_column :rolls, :rent_due_1818_B, :float
    add_column :rolls, :rent_paid_1818_B, :float
    add_column :rolls, :rent_owed_1818_B, :float
    add_column :rolls, :rent_ontime_1818_B, :boolean
    add_column :rolls, :rent_payment_method_1818_B, :string
    add_column :rolls, :rent_due_1818_A, :float
    add_column :rolls, :rent_paid_1818_A, :float
    add_column :rolls, :rent_owed_1818_A, :float
    add_column :rolls, :rent_ontime_1818_A, :boolean
    add_column :rolls, :rent_payment_method_1818_A, :string
    add_column :rolls, :rent_due_1818_C, :float
    add_column :rolls, :rent_paid_1818_C, :float
    add_column :rolls, :rent_owed_1818_C, :float
    add_column :rolls, :rent_ontime_1818_C, :boolean
    add_column :rolls, :rent_payment_method_1818_C, :string
    add_column :rolls, :rent_due_1818_D, :float
    add_column :rolls, :rent_paid_1818_D, :float
    add_column :rolls, :rent_owed_1818_D, :float
    add_column :rolls, :rent_ontime_1818_D, :boolean
    add_column :rolls, :rent_payment_method_1818_D, :string
    add_column :rolls, :rent_due_1241_1, :float
    add_column :rolls, :rent_paid_1241_1, :float
    add_column :rolls, :rent_owed_1241_1, :float
    add_column :rolls, :rent_ontime_1241_1, :boolean
    add_column :rolls, :rent_payment_method_1241_1, :string
    add_column :rolls, :rent_due_1241_3, :float
    add_column :rolls, :rent_paid_1241_3, :float
    add_column :rolls, :rent_owed_1241_3, :float
    add_column :rolls, :rent_ontime_1241_3, :boolean
    add_column :rolls, :rent_payment_method_1241_3, :string
    add_column :rolls, :rent_due_1241_2, :float
    add_column :rolls, :rent_paid_1241_2, :float
    add_column :rolls, :rent_owed_1241_2, :float
    add_column :rolls, :rent_ontime_1241_2, :boolean
    add_column :rolls, :rent_payment_method_1241_2, :string
    add_column :rolls, :rent_due_1241_4, :float
    add_column :rolls, :rent_paid_1241_4, :float
    add_column :rolls, :rent_owed_1241_4, :float
    add_column :rolls, :rent_ontime_1241_4, :boolean
    add_column :rolls, :rent_payment_method_1241_4, :string
    add_column :rolls, :rent_due_1241_5, :float
    add_column :rolls, :rent_paid_1241_5, :float
    add_column :rolls, :rent_owed_1241_5, :float
    add_column :rolls, :rent_ontime_1241_5, :boolean
    add_column :rolls, :rent_payment_method_1241_5, :string
    add_column :rolls, :rent_due_1241_6, :float
    add_column :rolls, :rent_paid_1241_6, :float
    add_column :rolls, :rent_owed_1241_6, :float
    add_column :rolls, :rent_ontime_1241_6, :boolean
    add_column :rolls, :rent_payment_method_1241_6, :string
    add_column :rolls, :rent_due_1241_7, :float
    add_column :rolls, :rent_paid_1241_7, :float
    add_column :rolls, :rent_owed_1241_7, :float
    add_column :rolls, :rent_ontime_1241_7, :boolean
    add_column :rolls, :rent_payment_method_1241_7, :string
    add_column :rolls, :rent_due_1241_8, :float
    add_column :rolls, :rent_paid_1241_8, :float
    add_column :rolls, :rent_owed_1241_8, :float
    add_column :rolls, :rent_ontime_1241_8, :boolean
    add_column :rolls, :rent_payment_method_1241_8, :string
    add_column :rolls, :rent_due_1241_9, :float
    add_column :rolls, :rent_paid_1241_9, :float
    add_column :rolls, :rent_owed_1241_9, :float
    add_column :rolls, :rent_ontime_1241_9, :boolean
    add_column :rolls, :rent_payment_method_1241_9, :string
    add_column :rolls, :rent_due_1723_1, :float
    add_column :rolls, :rent_paid_1723_1, :float
    add_column :rolls, :rent_owed_1723_1, :float
    add_column :rolls, :rent_ontime_1723_1, :boolean
    add_column :rolls, :rent_payment_method_1723_1, :string
    add_column :rolls, :rent_due_1723_3, :float
    add_column :rolls, :rent_paid_1723_3, :float
    add_column :rolls, :rent_owed_1723_3, :float
    add_column :rolls, :rent_ontime_1723_3, :boolean
    add_column :rolls, :rent_payment_method_1723_3, :string
    add_column :rolls, :rent_due_1723_2, :float
    add_column :rolls, :rent_paid_1723_2, :float
    add_column :rolls, :rent_owed_1723_2, :float
    add_column :rolls, :rent_ontime_1723_2, :boolean
    add_column :rolls, :rent_payment_method_1723_2, :string
    add_column :rolls, :rent_due_1723_4, :float
    add_column :rolls, :rent_paid_1723_4, :float
    add_column :rolls, :rent_owed_1723_4, :float
    add_column :rolls, :rent_ontime_1723_4, :boolean
    add_column :rolls, :rent_payment_method_1723_4, :string
    add_column :rolls, :rent_due_1723_5, :float
    add_column :rolls, :rent_paid_1723_5, :float
    add_column :rolls, :rent_owed_1723_5, :float
    add_column :rolls, :rent_ontime_1723_5, :boolean
    add_column :rolls, :rent_payment_method_1723_5, :string
    add_column :rolls, :rent_due_2462_B, :float
    add_column :rolls, :rent_paid_2462_B, :float
    add_column :rolls, :rent_owed_2462_B, :float
    add_column :rolls, :rent_ontime_2462_B, :boolean
    add_column :rolls, :rent_payment_method_2462_B, :string
    add_column :rolls, :rent_due_2462_A, :float
    add_column :rolls, :rent_paid_2462_A, :float
    add_column :rolls, :rent_owed_2462_A, :float
    add_column :rolls, :rent_ontime_2462_A, :boolean
    add_column :rolls, :rent_payment_method_2462_A, :string
    add_column :rolls, :rent_due_2462_C, :float
    add_column :rolls, :rent_paid_2462_C, :float
    add_column :rolls, :rent_owed_2462_C, :float
    add_column :rolls, :rent_ontime_2462_C, :boolean
    add_column :rolls, :rent_payment_method_2462_C, :string
  end
end
